# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Korey Jackson'
tagline:          'experiments in digital publishing'
description:      '<a href="https://twitter.com/koreybjackson" target="_blank">@koreybjackson</a>'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde